import { Car, SafetyFeature } from '@/types';

export const safetyFeaturesDatabase: SafetyFeature[] = [
  {
    id: 'pilot-assist',
    name: 'Pilot Assist',
    category: 'driver-assistance',
    description: 'Adaptive cruise control with steering assistance that helps keep the car centered in its lane and maintains a set distance to the vehicle ahead.',
    icon: 'steering-wheel',
    details: [
      'Works at speeds up to 130 km/h',
      'Automatic acceleration and braking',
      'Lane centering assistance',
      'Stop & Go functionality in traffic',
      'Curve speed adaptation',
    ],
    standard: true,
  },
  {
    id: 'city-safety',
    name: 'City Safety',
    category: 'active',
    description: 'Autonomous emergency braking system that detects vehicles, pedestrians, cyclists, and large animals day and night.',
    icon: 'shield-check',
    details: [
      'Detects vehicles, pedestrians, cyclists, large animals',
      'Active at speeds 4-130 km/h (vehicles), 4-80 km/h (pedestrians/cyclists)',
      'Automatic braking if collision imminent',
      'Audible and visual warnings before braking',
      'Intersection support for crossing traffic',
    ],
    standard: true,
  },
  {
    id: 'blis',
    name: 'Blind Spot Information System (BLIS)',
    category: 'driver-assistance',
    description: 'Alerts you to vehicles in your blind spots with a visible indicator in the side mirrors and active steering assistance.',
    icon: 'radar',
    details: [
      'Visual indicator in side mirrors',
      'Steer assist intervention if changing lanes',
      'Works at speeds above 10 km/h',
      'Detects vehicles up to 70m behind',
      'Cross Traffic Alert when reversing',
    ],
    standard: true,
  },
  {
    id: 'run-off-road',
    name: 'Run-off Road Mitigation',
    category: 'active',
    description: 'Helps prevent the car from leaving the road unintentionally by providing steering assistance and braking.',
    icon: 'road',
    details: [
      'Detects road edges and lane markings',
      'Steering assistance to keep on road',
      'Braking intervention if needed',
      'Active between 65-140 km/h',
      'Tightens seat belts as precaution',
    ],
    standard: true,
  },
  {
    id: 'oncoming-lane',
    name: 'Oncoming Lane Mitigation',
    category: 'active',
    description: 'Helps prevent head-on collisions by detecting oncoming vehicles and providing steering assistance back into your lane.',
    icon: 'car-front',
    details: [
      'Detects oncoming vehicles',
      'Steering assistance to return to lane',
      'Active between 60-140 km/h',
      'Works on roads with visible lane markings',
      'Audible and visual warnings',
    ],
    standard: true,
  },
  {
    id: 'driver-alert',
    name: 'Driver Alert Control',
    category: 'driver-assistance',
    description: 'Monitors driving behavior and alerts the driver if signs of drowsiness or inattention are detected.',
    icon: 'coffee',
    details: [
      'Analyzes steering patterns',
      'Audible and visual alerts',
      'Suggests rest stops nearby',
      'Works at speeds above 65 km/h',
      'Resets after significant break',
    ],
    standard: true,
  },
  {
    id: '360-camera',
    name: '360° Surround View Camera',
    category: 'driver-assistance',
    description: 'Bird\'s-eye view camera system for easier parking and maneuvering in tight spaces.',
    icon: 'camera',
    details: [
      'Four wide-angle cameras',
      'Bird\'s-eye composite view',
      'Front, rear, and side views',
      'Dynamic guidelines for steering',
      'Obstacle detection with distance markers',
    ],
    standard: false,
  },
  {
    id: 'head-up-display',
    name: 'Head-Up Display',
    category: 'driver-assistance',
    description: 'Projects key information onto the windshield so you can keep your eyes on the road.',
    icon: 'projection-screen',
    details: [
      'Speed and navigation directions',
      'Traffic sign information',
      'Pilot Assist status',
      'Incoming calls and messages',
      'Adjustable brightness and position',
    ],
    standard: false,
  },
  {
    id: 'adaptive-headlights',
    name: 'Active Bending Lights',
    category: 'active',
    description: 'LED headlights that follow the curve of the road for better visibility in corners.',
    icon: 'light',
    details: [
      'Curve illumination up to 15 degrees',
      'Automatic high beam control',
      'Glare-free high beam technology',
      'Cornering lights at low speeds',
      'Adaptive to speed and steering angle',
    ],
    standard: true,
  },
  {
    id: 'airbags',
    name: 'Advanced Airbag System',
    category: 'passive',
    description: 'Comprehensive airbag protection including driver, passenger, side, curtain, and knee airbags.',
    icon: 'airbag',
    details: [
      'Dual-stage driver and passenger airbags',
      'Side impact airbags (front seats)',
      'Inflatable Curtains (IC) for all rows',
      'Driver knee airbag',
      'Front passenger weight sensor',
      'Whiplash protection system (WHIPS)',
    ],
    standard: true,
  },
  {
    id: 'safety-cage',
    name: 'Boron Steel Safety Cage',
    category: 'structural',
    description: 'Ultra-high strength boron steel construction forms a protective cage around occupants.',
    icon: 'shield',
    details: [
      'Boron steel in critical structural areas',
      'Front and rear crumple zones',
      'Side impact protection beams',
      'Reinforced roof structure',
      'Optimized energy absorption',
    ],
    standard: true,
  },
  {
    id: 'whips',
    name: 'Whiplash Protection System (WHIPS)',
    category: 'passive',
    description: 'Front seats designed to move with the occupant in a rear impact, reducing whiplash injuries.',
    icon: 'seat',
    details: [
      'Special seat hinge and frame design',
      'Absorbs rear impact energy',
      'Reduces neck acceleration by 50%',
      'Integrated into front seat design',
      'Tested for various impact speeds',
    ],
    standard: true,
  },
  {
    id: 'sip',
    name: 'Side Impact Protection System (SIPS)',
    category: 'structural',
    description: 'Energy-absorbing structure in doors and seats that channels impact forces away from occupants.',
    icon: 'car-side',
    details: [
      'Reinforced door structures',
      'Energy-absorbing door padding',
      'Cross-car beam in front seats',
      'Side airbags integrated with SIPS',
      'Protects chest and hip areas',
    ],
    standard: true,
  },
  {
    id: 'speed-limiter',
    name: 'Speed Limiter',
    category: 'driver-assistance',
    description: 'Allows the driver to set a maximum speed that the car will not exceed.',
    icon: 'gauge',
    details: [
      'Adjustable maximum speed setting',
      'Override by pressing accelerator firmly',
      'Visual indicator in driver display',
      'Works with Pilot Assist',
      'Can be linked to traffic sign recognition',
    ],
    standard: true,
  },
  {
    id: 'traffic-sign',
    name: 'Traffic Sign Recognition',
    category: 'driver-assistance',
    description: 'Detects and displays speed limits and other traffic signs in the driver display.',
    icon: 'sign',
    details: [
      'Recognizes speed limit signs',
      'Displays in driver display and HUD',
      'Works with Speed Limiter',
      'Updates automatically',
      'School zone and variable speed limits',
    ],
    standard: true,
  },
  {
    id: 'park-assist',
    name: 'Park Assist Pilot',
    category: 'driver-assistance',
    description: 'Automated parking system that handles steering, acceleration, and braking for parallel and perpendicular parking.',
    icon: 'parking',
    details: [
      'Automatic parking space detection',
      'Controls steering, acceleration, braking',
      'Parallel and perpendicular parking',
      'Exit assistance for parallel parking',
      'Driver monitors and can intervene',
    ],
    standard: false,
  },
  {
    id: 'emergency-stop',
    name: 'Emergency Stop Assist',
    category: 'active',
    description: 'If the driver becomes unresponsive, the car can bring itself to a controlled stop in its lane.',
    icon: 'alert-triangle',
    details: [
      'Activates after repeated warnings ignored',
      'Controlled deceleration to stop',
      'Activates hazard lights',
      'Unlocks doors for emergency access',
      'Calls emergency services (Volvo On Call)',
    ],
    standard: false,
  },
  {
    id: 'rear-collision',
    name: 'Rear Collision Warning & Mitigation',
    category: 'active',
    description: 'Warns following vehicles with rapid flashing lights and prepares the car for rear impact.',
    icon: 'bell',
    details: [
      'Flashes hazard lights rapidly',
      'Pre-tensions front seat belts',
      'Activates brakes to reduce forward motion',
      'Works at standstill and low speeds',
      'Reduces whiplash risk',
    ],
    standard: true,
  },
  {
    id: 'child-safety',
    name: 'Child Safety Features',
    category: 'passive',
    description: 'Integrated child booster cushions and ISOFIX anchor points for secure child seat installation.',
    icon: 'baby',
    details: [
      'Two-stage integrated booster cushions',
      'ISOFIX anchors in rear seats',
      'Top tether anchors',
      'Power child locks (rear doors)',
      'Rear-facing child seat compatible',
    ],
    standard: true,
  },
];

const baseSafetyFeatures = [
  'pilot-assist',
  'city-safety',
  'blis',
  'run-off-road',
  'oncoming-lane',
  'driver-alert',
  'adaptive-headlights',
  'airbags',
  'safety-cage',
  'whips',
  'sip',
  'speed-limiter',
  'traffic-sign',
  'rear-collision',
  'child-safety',
];

const premiumSafetyFeatures = [
  ...baseSafetyFeatures,
  '360-camera',
  'head-up-display',
  'park-assist',
  'emergency-stop',
];

export const volvoCars: Car[] = [
  {
    id: 'volvo-ex90-2026',
    model: 'EX90',
    year: 2026,
    trim: 'Ultra Twin Motor AWD',
    price: 78990000,
    originalPrice: 82990000,
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1619767415242-d27d6a3b63e5?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=300&fit=crop',
    specs: {
      engine: 'Dual Electric Motors',
      power: '380 kW (517 hp)',
      torque: '910 Nm',
      acceleration: '4.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '600 km (WLTP)',
      batteryCapacity: '111 kWh',
      chargingTime: '30 min (10-80% DC fast charge)',
      fuelEconomy: '21 kWh/100km',
      co2Emissions: '0 g/km',
      dimensions: {
        length: '5040 mm',
        width: '1960 mm',
        height: '1747 mm',
        wheelbase: '2984 mm',
      },
      weight: '2818 kg',
      cargoCapacity: '655 L (7 seats) / 2220 L (2 seats)',
      towingCapacity: '2200 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'electric',
    fuelType: 'electric',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 7,
    description: 'The Volvo EX90 is our flagship fully electric SUV, designed from the ground up for the electric age. With cutting-edge safety technology, impressive range, and luxurious Scandinavian design, it represents the future of Volvo.',
    highlights: [
      'Core Computing with NVIDIA DRIVE Orin',
      'LiDAR standard for autonomous driving readiness',
      'Bi-directional charging capability',
      'Sustainable interior materials',
      'Over-the-air updates',
    ],
    isNew: true,
    isPopular: true,
    discount: 5,
  },
  {
    id: 'volvo-ex30-2026',
    model: 'EX30',
    year: 2026,
    trim: 'Ultra Single Motor Extended Range',
    price: 42990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: 'Single Electric Motor (RWD)',
      power: '200 kW (272 hp)',
      torque: '343 Nm',
      acceleration: '5.3s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '480 km (WLTP)',
      batteryCapacity: '69 kWh',
      chargingTime: '26 min (10-80% DC fast charge)',
      fuelEconomy: '16.5 kWh/100km',
      co2Emissions: '0 g/km',
      dimensions: {
        length: '4233 mm',
        width: '1837 mm',
        height: '1549 mm',
        wheelbase: '2650 mm',
      },
      weight: '1895 kg',
      cargoCapacity: '318 L (5 seats) / 1040 L (2 seats)',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'electric',
    fuelType: 'electric',
    transmission: 'automatic',
    drivetrain: 'RWD',
    seating: 5,
    description: 'The Volvo EX30 is our compact electric SUV designed for city life. Small on the outside, big on the inside, with all the safety and technology you expect from Volvo in a more affordable package.',
    highlights: [
      'Compact city-friendly dimensions',
      'Minimalist Scandinavian interior',
      'Google built-in infotainment',
      'Park Assist Pilot available',
      'Fast charging to 80% in 26 minutes',
    ],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'volvo-xc90-2026',
    model: 'XC90',
    year: 2026,
    trim: 'Recharge Ultimate T8 AWD',
    price: 85990000,
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Twincharged + Electric Motor',
      power: '335 kW (455 hp)',
      torque: '709 Nm',
      acceleration: '5.3s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '75 km (electric only, WLTP)',
      batteryCapacity: '18.8 kWh',
      chargingTime: '3-5 hours (AC charging)',
      fuelEconomy: '1.5 L/100km (combined)',
      co2Emissions: '34 g/km',
      dimensions: {
        length: '4953 mm',
        width: '1959 mm',
        height: '1776 mm',
        wheelbase: '2984 mm',
      },
      weight: '2425 kg',
      cargoCapacity: '302 L (7 seats) / 1868 L (2 seats)',
      towingCapacity: '2400 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'suv',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 7,
    description: 'The Volvo XC90 Recharge is our flagship plug-in hybrid SUV, combining powerful performance with electric efficiency. Three rows of seats, premium materials, and advanced safety make it the ultimate family vehicle.',
    highlights: [
      'T8 Twin Engine AWD performance',
      'Pure electric range for daily commutes',
      'Bowers & Wilkins premium audio',
      '4-zone climate control',
      'Panoramic sunroof',
    ],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'volvo-xc60-2026',
    model: 'XC60',
    year: 2026,
    trim: 'Recharge Ultimate T6 AWD',
    price: 62990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Turbocharged + Electric Motor',
      power: '265 kW (360 hp)',
      torque: '540 Nm',
      acceleration: '5.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '81 km (electric only, WLTP)',
      batteryCapacity: '18.8 kWh',
      chargingTime: '3-5 hours (AC charging)',
      fuelEconomy: '1.4 L/100km (combined)',
      co2Emissions: '31 g/km',
      dimensions: {
        length: '4708 mm',
        width: '1902 mm',
        height: '1658 mm',
        wheelbase: '2865 mm',
      },
      weight: '2140 kg',
      cargoCapacity: '483 L (5 seats) / 1410 L (2 seats)',
      towingCapacity: '2100 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'suv',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo XC60 Recharge is our mid-size plug-in hybrid SUV, offering the perfect balance of size, performance, and efficiency. Ideal for families who want premium features without the full-size SUV footprint.',
    highlights: [
      'T6 Plug-in Hybrid powertrain',
      'Google Automotive Services built-in',
      'Harman Kardon premium audio',
      'Air purifier with PM2.5 sensor',
      'Hands-free power tailgate',
    ],
    isNew: true,
  },
  {
    id: 'volvo-xc40-2026',
    model: 'XC40',
    year: 2026,
    trim: 'Recharge Ultimate Twin Motor',
    price: 51990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: 'Dual Electric Motors',
      power: '300 kW (408 hp)',
      torque: '660 Nm',
      acceleration: '4.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '460 km (WLTP)',
      batteryCapacity: '78 kWh',
      chargingTime: '28 min (10-80% DC fast charge)',
      fuelEconomy: '18.5 kWh/100km',
      co2Emissions: '0 g/km',
      dimensions: {
        length: '4440 mm',
        width: '1873 mm',
        height: '1652 mm',
        wheelbase: '2702 mm',
      },
      weight: '2185 kg',
      cargoCapacity: '413 L (5 seats) / 1328 L (2 seats)',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'electric',
    fuelType: 'electric',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo XC40 Recharge is our compact electric SUV with bold design and impressive performance. Twin motor all-wheel drive delivers instant acceleration, while the elevated seating position gives you a commanding view.',
    highlights: [
      'Twin Motor AWD performance',
      'Frunk (front trunk) for extra storage',
      'Pixel LED headlights with adaptive bending',
      'Fixed panoramic glass roof',
      'Recycled interior materials',
    ],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'volvo-s90-2025',
    model: 'S90',
    year: 2025,
    trim: 'Recharge Ultimate T8 AWD',
    price: 72990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Twincharged + Electric Motor',
      power: '335 kW (455 hp)',
      torque: '709 Nm',
      acceleration: '5.0s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '78 km (electric only, WLTP)',
      batteryCapacity: '18.8 kWh',
      chargingTime: '3-5 hours (AC charging)',
      fuelEconomy: '1.3 L/100km (combined)',
      co2Emissions: '29 g/km',
      dimensions: {
        length: '5090 mm',
        width: '1879 mm',
        height: '1450 mm',
        wheelbase: '3061 mm',
      },
      weight: '2180 kg',
      cargoCapacity: '404 L',
      towingCapacity: '2000 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'sedan',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo S90 Recharge is our flagship executive sedan, combining elegant Scandinavian design with advanced plug-in hybrid technology. A refined driving experience with class-leading safety.',
    highlights: [
      'Executive sedan proportions',
      'Bowers & Wilkins 1400W audio system',
      'Massaging front seats with ventilation',
      'Rear seat entertainment system',
      'Crystal gear lever by Orrefors',
    ],
    isPopular: true,
  },
  {
    id: 'volvo-v90-2025',
    model: 'V90 Cross Country',
    year: 2025,
    trim: 'Ultimate B6 AWD',
    price: 68990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '220 kW (299 hp)',
      torque: '420 Nm',
      acceleration: '6.2s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.8 L/100km (combined)',
      co2Emissions: '177 g/km',
      dimensions: {
        length: '4945 mm',
        width: '1902 mm',
        height: '1544 mm',
        wheelbase: '2941 mm',
      },
      weight: '1955 kg',
      cargoCapacity: '560 L (5 seats) / 1526 L (2 seats)',
      towingCapacity: '2200 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'wagon',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo V90 Cross Country is our premium all-road wagon, combining the elegance of a sedan with the versatility of an SUV. Higher ground clearance and all-wheel drive make it ready for any adventure.',
    highlights: [
      'Cross Country elevated suspension',
      'All-wheel drive as standard',
      'Integrated roof rails',
      'Flexible cargo divider system',
      'Off-road driving modes',
    ],
    isPopular: true,
  },
  {
    id: 'volvo-s60-2025',
    model: 'S60',
    year: 2025,
    trim: 'Recharge Ultimate T6 AWD',
    price: 55990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Turbocharged + Electric Motor',
      power: '265 kW (360 hp)',
      torque: '540 Nm',
      acceleration: '5.4s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '85 km (electric only, WLTP)',
      batteryCapacity: '18.8 kWh',
      chargingTime: '3-5 hours (AC charging)',
      fuelEconomy: '1.2 L/100km (combined)',
      co2Emissions: '27 g/km',
      dimensions: {
        length: '4761 mm',
        width: '1850 mm',
        height: '1431 mm',
        wheelbase: '2872 mm',
      },
      weight: '1985 kg',
      cargoCapacity: '409 L',
      towingCapacity: '1800 kg',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'sedan',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo S60 Recharge is our dynamic sports sedan with plug-in hybrid power. Sharp handling, striking design, and advanced safety make it the driver\'s choice in the premium sedan segment.',
    highlights: [
      'Sport-tuned chassis',
      'T6 Plug-in Hybrid performance',
      'Integrated Google Assistant',
      'Head-Up Display available',
      'Polestar Engineered variant available',
    ],
  },
  {
    id: 'volvo-v60-2025',
    model: 'V60 Cross Country',
    year: 2025,
    trim: 'Ultimate B5 AWD',
    price: 52990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '184 kW (250 hp)',
      torque: '350 Nm',
      acceleration: '6.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.2 L/100km (combined)',
      co2Emissions: '164 g/km',
      dimensions: {
        length: '4785 mm',
        width: '1850 mm',
        height: '1501 mm',
        wheelbase: '2872 mm',
      },
      weight: '1845 kg',
      cargoCapacity: '519 L (5 seats) / 1431 L (2 seats)',
      towingCapacity: '2000 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'wagon',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo V60 Cross Country is our versatile mid-size wagon with rugged styling and all-road capability. Perfect for active lifestyles that demand both style and substance.',
    highlights: [
      'Cross Country ground clearance',
      'B5 Mild Hybrid efficiency',
      'Versatile cargo space',
      'Advanced driver assistance',
      'Premium interior materials',
    ],
  },
  {
    id: 'volvo-c40-2025',
    model: 'C40 Recharge',
    year: 2025,
    trim: 'Twin Motor Ultimate',
    price: 54990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: 'Dual Electric Motors',
      power: '300 kW (408 hp)',
      torque: '660 Nm',
      acceleration: '4.7s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '445 km (WLTP)',
      batteryCapacity: '78 kWh',
      chargingTime: '28 min (10-80% DC fast charge)',
      fuelEconomy: '19.2 kWh/100km',
      co2Emissions: '0 g/km',
      dimensions: {
        length: '4440 mm',
        width: '1873 mm',
        height: '1591 mm',
        wheelbase: '2702 mm',
      },
      weight: '2165 kg',
      cargoCapacity: '413 L (5 seats) / 1205 L (2 seats)',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'electric',
    fuelType: 'electric',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo C40 Recharge is our coupe-style electric SUV with a sloping roofline and bold design. All the performance and safety of the XC40 Recharge in a more distinctive package.',
    highlights: [
      'Coupe-SUV silhouette',
      'Leather-free interior as standard',
      'Pixel LED headlights',
      'Fixed panoramic glass roof',
      'Over-the-air updates',
    ],
    isNew: true,
  },
  {
    id: 'volvo-xc90-2024',
    model: 'XC90',
    year: 2024,
    trim: 'B6 AWD Plus',
    price: 64990000,
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '220 kW (299 hp)',
      torque: '420 Nm',
      acceleration: '6.7s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '8.5 L/100km (combined)',
      co2Emissions: '192 g/km',
      dimensions: {
        length: '4953 mm',
        width: '1959 mm',
        height: '1776 mm',
        wheelbase: '2984 mm',
      },
      weight: '2185 kg',
      cargoCapacity: '302 L (7 seats) / 1868 L (2 seats)',
      towingCapacity: '2400 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'suv',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 7,
    description: 'The Volvo XC90 B6 is our seven-seat luxury SUV with mild hybrid technology. Spacious, safe, and sophisticated, it\'s designed for modern family life.',
    highlights: [
      'Seven versatile seats',
      'B6 Mild Hybrid efficiency',
      'CleanZone air quality system',
      'Integrated child booster seats',
      'Hands-free tailgate',
    ],
  },
  {
    id: 'volvo-xc60-2024',
    model: 'XC60',
    year: 2024,
    trim: 'B5 AWD Plus',
    price: 51990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '184 kW (250 hp)',
      torque: '350 Nm',
      acceleration: '7.1s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.6 L/100km (combined)',
      co2Emissions: '172 g/km',
      dimensions: {
        length: '4708 mm',
        width: '1902 mm',
        height: '1658 mm',
        wheelbase: '2865 mm',
      },
      weight: '1945 kg',
      cargoCapacity: '483 L (5 seats) / 1410 L (2 seats)',
      towingCapacity: '2100 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'suv',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo XC60 B5 is our best-selling mid-size SUV, offering the perfect blend of size, performance, and value. Mild hybrid technology improves efficiency without compromising driving dynamics.',
    highlights: [
      'B5 Mild Hybrid powertrain',
      'Google built-in infotainment',
      'Wireless phone charging',
      'Panoramic sunroof',
      'Power fold rear headrests',
    ],
    isPopular: true,
  },
  {
    id: 'volvo-xc40-2024',
    model: 'XC40',
    year: 2024,
    trim: 'B4 AWD Plus',
    price: 41990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '145 kW (197 hp)',
      torque: '300 Nm',
      acceleration: '7.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.1 L/100km (combined)',
      co2Emissions: '161 g/km',
      dimensions: {
        length: '4440 mm',
        width: '1873 mm',
        height: '1652 mm',
        wheelbase: '2702 mm',
      },
      weight: '1785 kg',
      cargoCapacity: '460 L (5 seats) / 1336 L (2 seats)',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'suv',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo XC40 B4 is our compact luxury SUV, winner of numerous awards for its design, safety, and urban practicality. Perfect for city driving with premium features throughout.',
    highlights: [
      'Compact city-friendly size',
      'Award-winning design',
      'B4 Mild Hybrid efficiency',
      'Harman Kardon audio available',
      'Wireless Apple CarPlay',
    ],
  },
  {
    id: 'volvo-s90-2023',
    model: 'S90',
    year: 2023,
    trim: 'Recharge T6 AWD Inscription',
    price: 58990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Turbocharged + Electric Motor',
      power: '265 kW (360 hp)',
      torque: '540 Nm',
      acceleration: '5.2s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '56 km (electric only, WLTP)',
      batteryCapacity: '11.6 kWh',
      chargingTime: '3-4 hours (AC charging)',
      fuelEconomy: '1.8 L/100km (combined)',
      co2Emissions: '41 g/km',
      dimensions: {
        length: '5090 mm',
        width: '1879 mm',
        height: '1450 mm',
        wheelbase: '3061 mm',
      },
      weight: '2085 kg',
      cargoCapacity: '404 L',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'sedan',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The Volvo S90 Recharge T6 is our executive plug-in hybrid sedan from 2023, offering refined luxury with electric efficiency for the daily commute.',
    highlights: [
      'T6 Plug-in Hybrid powertrain',
      'Inscription luxury trim',
      'Bowers & Wilkins audio',
      'Nappa leather upholstery',
      'Massaging front seats',
    ],
  },
  {
    id: 'volvo-v90-2023',
    model: 'V90 Cross Country',
    year: 2023,
    trim: 'B6 AWD Pro',
    price: 54990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '220 kW (299 hp)',
      torque: '420 Nm',
      acceleration: '6.4s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '8.1 L/100km (combined)',
      co2Emissions: '184 g/km',
      dimensions: {
        length: '4945 mm',
        width: '1902 mm',
        height: '1544 mm',
        wheelbase: '2941 mm',
      },
      weight: '1945 kg',
      cargoCapacity: '560 L (5 seats) / 1526 L (2 seats)',
      towingCapacity: '2200 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'wagon',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2023 Volvo V90 Cross Country combines wagon practicality with SUV capability. Elegant design meets all-road versatility in this premium estate.',
    highlights: [
      'Cross Country capability',
      'B6 Mild Hybrid performance',
      'Integrated roof load carriers',
      'Flexible cargo solutions',
      'Advanced climate system',
    ],
  },
  {
    id: 'volvo-s60-2023',
    model: 'S60',
    year: 2023,
    trim: 'B5 AWD Plus',
    price: 42990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '184 kW (250 hp)',
      torque: '350 Nm',
      acceleration: '6.6s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.0 L/100km (combined)',
      co2Emissions: '159 g/km',
      dimensions: {
        length: '4761 mm',
        width: '1850 mm',
        height: '1431 mm',
        wheelbase: '2872 mm',
      },
      weight: '1785 kg',
      cargoCapacity: '409 L',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'sedan',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2023 Volvo S60 B5 is our dynamic sports sedan with mild hybrid efficiency. Sharp design, engaging driving dynamics, and class-leading safety.',
    highlights: [
      'Sport sedan dynamics',
      'B5 Mild Hybrid efficiency',
      'Google services built-in',
      '12.3" digital driver display',
      'Premium audio available',
    ],
  },
  {
    id: 'volvo-v60-2022',
    model: 'V60',
    year: 2022,
    trim: 'B5 AWD Inscription',
    price: 46990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '184 kW (250 hp)',
      torque: '350 Nm',
      acceleration: '6.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.1 L/100km (combined)',
      co2Emissions: '161 g/km',
      dimensions: {
        length: '4762 mm',
        width: '1850 mm',
        height: '1437 mm',
        wheelbase: '2872 mm',
      },
      weight: '1795 kg',
      cargoCapacity: '519 L (5 seats) / 1431 L (2 seats)',
      towingCapacity: '1800 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'wagon',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2022 Volvo V60 B5 is our versatile sports wagon with mild hybrid technology. Elegant Scandinavian design meets practical cargo space and engaging driving dynamics.',
    highlights: [
      'Sports wagon versatility',
      'B5 Mild Hybrid efficiency',
      'Inscription luxury trim',
      'Integrated booster cushions',
      'Premium sound system',
    ],
  },
  {
    id: 'volvo-xc90-2022',
    model: 'XC90',
    year: 2022,
    trim: 'B6 AWD Inscription',
    price: 59990000,
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '220 kW (299 hp)',
      torque: '420 Nm',
      acceleration: '6.7s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '8.5 L/100km (combined)',
      co2Emissions: '192 g/km',
      dimensions: {
        length: '4953 mm',
        width: '1959 mm',
        height: '1776 mm',
        wheelbase: '2984 mm',
      },
      weight: '2185 kg',
      cargoCapacity: '302 L (7 seats) / 1868 L (2 seats)',
      towingCapacity: '2400 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'suv',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 7,
    description: 'The 2022 Volvo XC90 B6 is our seven-seat flagship SUV with mild hybrid power. Uncompromising safety, luxurious comfort, and versatile space for the whole family.',
    highlights: [
      'Seven-seat flexibility',
      'B6 Mild Hybrid performance',
      'Inscription luxury package',
      'Four-zone climate control',
      'Bowers & Wilkins audio',
    ],
  },
  {
    id: 'volvo-xc60-2022',
    model: 'XC60',
    year: 2022,
    trim: 'B5 AWD Momentum',
    price: 45990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Mild Hybrid Turbocharged',
      power: '184 kW (250 hp)',
      torque: '350 Nm',
      acceleration: '7.1s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '7.6 L/100km (combined)',
      co2Emissions: '172 g/km',
      dimensions: {
        length: '4708 mm',
        width: '1902 mm',
        height: '1658 mm',
        wheelbase: '2865 mm',
      },
      weight: '1945 kg',
      cargoCapacity: '483 L (5 seats) / 1410 L (2 seats)',
      towingCapacity: '2100 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'suv',
    fuelType: 'mild-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2022 Volvo XC60 B5 is our mid-size SUV sweet spot, offering premium features, excellent safety, and mild hybrid efficiency at an accessible price point.',
    highlights: [
      'Best-selling mid-size SUV',
      'B5 Mild Hybrid technology',
      'Clean interior design',
      'Comprehensive safety suite',
      'Excellent value proposition',
    ],
  },
  {
    id: 'volvo-xc40-2021',
    model: 'XC40',
    year: 2021,
    trim: 'Recharge Pure Electric P8 AWD',
    price: 49990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: 'Dual Electric Motors',
      power: '300 kW (408 hp)',
      torque: '660 Nm',
      acceleration: '4.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '418 km (WLTP)',
      batteryCapacity: '78 kWh',
      chargingTime: '33 min (10-80% DC fast charge)',
      fuelEconomy: '20.1 kWh/100km',
      co2Emissions: '0 g/km',
      dimensions: {
        length: '4440 mm',
        width: '1873 mm',
        height: '1652 mm',
        wheelbase: '2702 mm',
      },
      weight: '2185 kg',
      cargoCapacity: '413 L (5 seats) / 1328 L (2 seats)',
    },
    safetyFeatures: premiumSafetyFeatures,
    category: 'electric',
    fuelType: 'electric',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2021 Volvo XC40 Recharge was our first fully electric car, pioneering our electric future. Twin motor all-wheel drive, compact SUV practicality, and zero emissions.',
    highlights: [
      'Volvo\'s first fully electric car',
      'Twin Motor AWD performance',
      'Google Android Automotive OS',
      'Over-the-air updates',
      'Leather-free interior option',
    ],
  },
  {
    id: 'volvo-s90-2020',
    model: 'S90',
    year: 2020,
    trim: 'T8 Twin Engine AWD Inscription',
    price: 52990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Twincharged + Electric Motor',
      power: '297 kW (405 hp)',
      torque: '640 Nm',
      acceleration: '5.1s (0-100 km/h)',
      topSpeed: '180 km/h',
      range: '49 km (electric only, NEDC)',
      batteryCapacity: '11.6 kWh',
      chargingTime: '3-4 hours (AC charging)',
      fuelEconomy: '2.1 L/100km (combined)',
      co2Emissions: '48 g/km',
      dimensions: {
        length: '5090 mm',
        width: '1879 mm',
        height: '1450 mm',
        wheelbase: '3061 mm',
      },
      weight: '2035 kg',
      cargoCapacity: '404 L',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'sedan',
    fuelType: 'plug-in-hybrid',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2020 Volvo S90 T8 Twin Engine is our executive plug-in hybrid sedan, combining powerful performance with electric efficiency in a beautifully crafted package.',
    highlights: [
      'T8 Twin Engine performance',
      'Inscription luxury trim',
      'Crystal gear lever',
      'Bowers & Wilkins audio',
      'Massaging ventilated seats',
    ],
  },
  {
    id: 'volvo-v90-2020',
    model: 'V90 Cross Country',
    year: 2020,
    trim: 'T6 AWD Pro',
    price: 49990000,
    images: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&h=800&fit=crop',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=400&h=300&fit=crop',
    specs: {
      engine: '2.0L Twincharged',
      power: '235 kW (320 hp)',
      torque: '400 Nm',
      acceleration: '5.9s (0-100 km/h)',
      topSpeed: '180 km/h',
      fuelEconomy: '8.2 L/100km (combined)',
      co2Emissions: '186 g/km',
      dimensions: {
        length: '4945 mm',
        width: '1902 mm',
        height: '1544 mm',
        wheelbase: '2941 mm',
      },
      weight: '1895 kg',
      cargoCapacity: '560 L (5 seats) / 1526 L (2 seats)',
      towingCapacity: '2200 kg',
    },
    safetyFeatures: baseSafetyFeatures,
    category: 'wagon',
    fuelType: 'gasoline',
    transmission: 'automatic',
    drivetrain: 'AWD',
    seating: 5,
    description: 'The 2020 Volvo V90 Cross Country T6 is our all-road wagon with twin-charged power. Sophisticated design, versatile cargo space, and all-weather capability.',
    highlights: [
      'T6 Twincharged performance',
      'Cross Country capability',
      'Pro trim level features',
      'Integrated roof rails',
      'All-wheel drive standard',
    ],
  },
];

export function getCarById(id: string): Car | undefined {
  return volvoCars.find(car => car.id === id);
}

export function getCarsByYear(year: number): Car[] {
  return volvoCars.filter(car => car.year === year);
}

export function getCarsByCategory(category: Car['category']): Car[] {
  return volvoCars.filter(car => car.category === category);
}

export function getNewCars(): Car[] {
  return volvoCars.filter(car => car.isNew);
}

export function getPopularCars(): Car[] {
  return volvoCars.filter(car => car.isPopular);
}

export function getSafetyFeatureById(id: string): SafetyFeature | undefined {
  return safetyFeaturesDatabase.find(feature => feature.id === id);
}

export function getSafetyFeaturesByIds(ids: string[]): SafetyFeature[] {
  return ids.map(id => getSafetyFeatureById(id)).filter(Boolean) as SafetyFeature[];
}